# Generated by Django 3.1.12 on 2025-06-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='id',
            new_name='_id',
        ),
    ]
