# Generated by Django 3.1.12 on 2025-06-05 14:04

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='delivery_boys/profile_pics/')),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='delivery_boys/aadhar/')),
                ('license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='delivery_boys/license/')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car')], max_length=20, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('idle', 'Idle'), ('on_delivery', 'On Delivery'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_boy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
