# Generated by Django 3.1.12 on 2025-06-07 07:55

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('items', djongo.models.fields.JSONField(help_text='List of product IDs, names, quantities, and prices')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions from user', null=True)),
                ('subtotal', models.FloatField()),
                ('tax', models.FloatField(default=0.0)),
                ('delivery_fee', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('total_price', models.FloatField()),
                ('coupon_code', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet')], default='Cash on Delivery', max_length=30)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], default='Delivery', max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('estimated_time_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Picked Up', 'Picked Up'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('is_rated', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(blank=True, max_length=20, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_boy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.deliveryboy')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
